# Generated by Django 5.2.11 on 2026-07-31 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.TextField()),
                ('phone', models.TextField(blank=True, default='')),
                ('email', models.TextField(blank=True, default='')),
                ('company_name', models.TextField(blank=True, default='')),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('sent', 'Sent · link active'), ('uploads_complete', 'Uploads complete'), ('expired', 'Link expired · no upload')], default='draft')),
                ('link_token', models.CharField(blank=True, max_length=48, null=True, unique=True)),
                ('link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
