# Generated by Django 5.2.11 on 2026-07-31 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.TextField()),
                ('from_email', models.TextField(default='requests@freedombankva.com')),
                ('subject', models.TextField()),
                ('body_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='document_requests.documentrequest')),
            ],
            options={
                'db_table': 'request_emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
