# Generated by Django 5.2.11 on 2026-07-31 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0002_requestemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestemail',
            name='kind',
            field=models.TextField(choices=[('request', 'Secure document request'), ('fraud_alert', 'Fraud/session-guard alert')], default='request'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.TextField(choices=[('draft', 'Draft'), ('sent', 'Sent · link active'), ('uploads_complete', 'Uploads complete'), ('expired', 'Link expired · no upload'), ('fraud_stopped', 'Session ended — fraud guard')], default='draft'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded')], default='pending')),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='document_requests.documentrequest')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_type', models.TextField()),
                ('file_path', models.TextField(help_text='Path relative to settings.UPLOAD_STORAGE_ROOT')),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='document_requests.checklistitem')),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='document_requests.documentrequest')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='current_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='document_requests.uploadedfile'),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('fraud_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('fraud_reason', models.TextField(blank=True, default='')),
                ('document_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='document_requests.documentrequest')),
            ],
            options={
                'db_table': 'upload_sessions',
            },
        ),
    ]
