# Generated by Django 5.2.11 on 2026-08-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0003_requestemail_kind_alter_documentrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requestemail',
            name='kind',
            field=models.TextField(choices=[('request', 'Secure document request'), ('fraud_alert', 'Fraud/session-guard alert'), ('confirmation', 'Upload completion confirmation')], default='request'),
        ),
    ]
