# Generated by Django 5.2.11 on 2026-08-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0004_documentrequest_reference_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='extraction_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='review_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='review_status',
            field=models.TextField(choices=[('pending', 'Pending review'), ('approved', 'Ready for extraction'), ('flagged', 'Flagged — re-upload')], default='pending'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestemail',
            name='kind',
            field=models.TextField(choices=[('request', 'Secure document request'), ('fraud_alert', 'Fraud/session-guard alert'), ('confirmation', 'Upload completion confirmation'), ('review_flags', 'Batched flagged-document re-request')], default='request'),
        ),
    ]
