# Generated by Django 5.2.11 on 2026-08-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0005_documentrequest_extraction_queued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.TextField(choices=[('relationship', 'Relationship'), ('entities', 'Entities'), ('covenant_ledger', 'Covenant ledger'), ('indicators', 'Indicators'), ('allocation', 'Allocation')], default='relationship')),
                ('relationship_at', models.DateTimeField(auto_now_add=True)),
                ('entities_at', models.DateTimeField(blank=True, null=True)),
                ('covenant_ledger_at', models.DateTimeField(blank=True, null=True)),
                ('indicators_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_at', models.DateTimeField(blank=True, null=True)),
                ('document_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_twin', to='document_requests.documentrequest')),
            ],
            options={
                'db_table': 'business_twins',
            },
        ),
        migrations.CreateModel(
            name='DocumentTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.TextField(choices=[('received', 'Received'), ('classified', 'Classified'), ('extracted', 'Extracted'), ('provenance', 'Provenance'), ('confidence', 'Confidence')], default='received')),
                ('classification_label', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('provenance_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_at', models.DateTimeField(blank=True, null=True)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_twins', to='document_requests.documentrequest')),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twin', to='document_requests.uploadedfile')),
            ],
            options={
                'db_table': 'document_twins',
            },
        ),
        migrations.CreateModel(
            name='ExtractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField()),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_events', to='document_requests.documentrequest')),
                ('document_twin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='document_requests.documenttwin')),
            ],
            options={
                'db_table': 'extraction_events',
                'ordering': ['created_at'],
            },
        ),
    ]
