# Generated by Django 5.2.11 on 2026-08-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0006_businesstwin_documenttwin_extractionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField()),
                ('value', models.TextField()),
                ('source', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField()),
                ('document_twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_values', to='document_requests.documenttwin')),
            ],
            options={
                'db_table': 'extracted_values',
                'ordering': ['id'],
            },
        ),
    ]
