# Generated by Django 5.2.11 on 2026-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0007_extractedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='audience',
            field=models.TextField(choices=[('lender', 'Lender · customer-facing'), ('loan_admin', 'Loan Admin · internal')], default='lender'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
    ]
