# Generated by Django 5.2.11 on 2026-08-01 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0008_checklistitem_audience_checklistitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_items', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklist_preferences',
            },
        ),
    ]
