# Generated by Django 5.2.11 on 2026-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0009_checklistpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestemail',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestemail',
            name='delivery_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
