# Generated by Django 5.2.11 on 2026-08-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0010_requestemail_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestemail',
            name='kind',
            field=models.TextField(choices=[('request', 'Secure document request'), ('fraud_alert', 'Fraud/session-guard alert'), ('confirmation', 'Upload completion confirmation'), ('review_flags', 'Batched flagged-document re-request'), ('discrepancy', 'Step 8 HITL discrepancy — customer query')], default='request'),
        ),
    ]
